actuator.c File Reference
#include `Include/actuator.h`
Functions
uint32_t Actuator_task ()
void Actuator_fn (void *pvParameters)
void ConfigureLED (void)
Variables
float back_lat
float back_lon
Function Documentation
Actuator_fn()
void Actuator_fn (void * pvParameters)
Definition at line 26 of file actuator.c.
References Accident_Addr, Back, back_lat, back_lon, ConfigureLCD(), ConfigureLED(), Dir_Addr, Fwd, GPS_Addr, gps_course_to(), Lat_Addr, lcdgotoaddr(), lcdputch(), lcdputfloat(), lcdputint(), lcdputstr(), Left, Lon_Addr, Misled, MPU_Addr, Reached, Rf_Addr, rf_link, Right, Satellite_Addr, xHandle_rf, xHandle_s, and xQueue_a.
Referenced by Actuator_task().
Actuator_task()
uint32_t Actuator_task ()
Definition at line 13 of file actuator.c.
References Actuator_fn(), and configMAX_PRIORITIES.
Referenced by main().
ConfigureLED()
void ConfigureLED (void)
Definition at line 160 of file actuator.c.
Referenced by Actuator_fn().
Variable Documentation
back_lat
float back_lat
File: actuator.c Author: Vatsal Sheth & Sarthak Jain Description: This file creates task for actuators which control LCD and LED Date: 4/29/2019
Definition at line 11 of file actuator.c.
Referenced by Actuator_fn().
back_lon
float back_lon
Definition at line 11 of file actuator.c.
Referenced by Actuator_fn().