Include/actuator.h File Reference
#include `lcd_driver.h`
Macros
#define Satellite_Addr (0x02)
#define Rf_Addr (0x08)
#define Accident_Addr (0x0f)
#define GPS_Addr (0x0d)
#define MPU_Addr (0x0e)
#define Lat_Addr (0x44)
#define Lon_Addr (0x14)
#define Dir_Addr (0x53)
#define Fwd (0x01)
#define Back (0x02)
#define Right (0x04)
#define Left (0x08)
#define Misled (0x10)
#define Reached (0x20)
Functions
uint32_t Actuator_task ()
void Actuator_fn (void *pvParameters)
void ConfigureLED (void)
float gps_course_to (float lat1, float long1, float lat2, float long2)
Variables
QueueHandle_t xQueue_rf
QueueHandle_t xQueue_a
SemaphoreHandle_t xSemaphore_rf
TaskHandle_t xHandle_s
TaskHandle_t xHandle_rf
uint32_t rf_link
Macro Definition Documentation
Accident_Addr
#define Accident_Addr (0x0f)
Definition at line 15 of file actuator.h.
Referenced by Actuator_fn().
Back
#define Back (0x02)
Definition at line 23 of file actuator.h.
Referenced by Actuator_fn().
Dir_Addr
#define Dir_Addr (0x53)
Definition at line 20 of file actuator.h.
Referenced by Actuator_fn().
Fwd
#define Fwd (0x01)
Definition at line 22 of file actuator.h.
Referenced by Actuator_fn().
GPS_Addr
#define GPS_Addr (0x0d)
Definition at line 16 of file actuator.h.
Referenced by Actuator_fn().
Lat_Addr
#define Lat_Addr (0x44)
Definition at line 18 of file actuator.h.
Referenced by Actuator_fn().
Left
#define Left (0x08)
Definition at line 25 of file actuator.h.
Referenced by Actuator_fn().
Lon_Addr
#define Lon_Addr (0x14)
Definition at line 19 of file actuator.h.
Referenced by Actuator_fn().
Misled
#define Misled (0x10)
Definition at line 26 of file actuator.h.
Referenced by Actuator_fn().
MPU_Addr
#define MPU_Addr (0x0e)
Definition at line 17 of file actuator.h.
Referenced by Actuator_fn().
Reached
#define Reached (0x20)
Definition at line 27 of file actuator.h.
Referenced by Actuator_fn().
Rf_Addr
#define Rf_Addr (0x08)
Definition at line 14 of file actuator.h.
Referenced by Actuator_fn().
Right
#define Right (0x04)
Definition at line 24 of file actuator.h.
Referenced by Actuator_fn().
Satellite_Addr
#define Satellite_Addr (0x02)
File: actuator.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by actuator.c Date: 4/29/2019
Definition at line 13 of file actuator.h.
Referenced by Actuator_fn().
Function Documentation
Actuator_fn()
void Actuator_fn (void * pvParameters)
Definition at line 26 of file actuator.c.
References Accident_Addr, Back, back_lat, back_lon, ConfigureLCD(), ConfigureLED(), Dir_Addr, Fwd, GPS_Addr, gps_course_to(), Lat_Addr, lcdgotoaddr(), lcdputch(), lcdputfloat(), lcdputint(), lcdputstr(), Left, Lon_Addr, Misled, MPU_Addr, Reached, Rf_Addr, rf_link, Right, Satellite_Addr, xHandle_rf, xHandle_s, and xQueue_a.
Referenced by Actuator_task().
Actuator_task()
uint32_t Actuator_task ()
Definition at line 13 of file actuator.c.
References Actuator_fn(), and configMAX_PRIORITIES.
Referenced by main().
ConfigureLED()
void ConfigureLED (void)
Definition at line 160 of file actuator.c.
Referenced by Actuator_fn().
gps_course_to()
float gps_course_to (float lat1, float long1, float lat2, float long2)
Parameters
lat1
long1
lat2
long2
Returns
Definition at line 438 of file gps_driver.c.
Referenced by Actuator_fn().
Variable Documentation
rf_link
uint32_t rf_link
Definition at line 12 of file rf_comm.c.
Referenced by Actuator_fn().
xHandle_rf
TaskHandle_t xHandle_rf
File: rf_comm.c Author: Vatsal Sheth & Sarthak Jain Description: This file creates task for rf comunication control Date: 4/29/2019
Definition at line 11 of file rf_comm.c.
Referenced by Actuator_fn().
xHandle_s
TaskHandle_t xHandle_s
Definition at line 12 of file sensor.c.
Referenced by Actuator_fn().
xQueue_a
QueueHandle_t xQueue_a
Definition at line 12 of file main.c.
Referenced by Actuator_fn(), Comm_fn(), and Sensor_fn().
xQueue_rf
QueueHandle_t xQueue_rf
Definition at line 12 of file main.c.
Referenced by Comm_fn(), and Sensor_fn().
xSemaphore_rf
SemaphoreHandle_t xSemaphore_rf
Definition at line 13 of file main.c.