Include/button.h File Reference
#include `basic.h`
Functions
void Button_ISR (void)
Button click.
void ConfigureButton ()
Configure On board user button on PJ0.
Variables
uint32_t button_flag
struct tx_packet pk
Function Documentation
Button_ISR()
void Button_ISR (void)
Button click.
Definition at line 25 of file button.c.
References button_flag, and pk.
Referenced by ConfigureButton().
ConfigureButton()
void ConfigureButton ()
Configure On board user button on PJ0.
File: button.c Author: Vatsal Sheth & Sarthak Jain Description: This file contains configuration and isr for user button Date: 4/29/2019
Definition at line 12 of file button.c.
References Button_ISR().
Referenced by Sensor_fn().
Variable Documentation
button_flag
uint32_t button_flag
File: button.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by button.c Date: 4/29/2019
File: sensor.c Author: Vatsal Sheth & Sarthak Jain Description: This file creates task for sensors which control GPS, MPU6050, button Date: 4/29/2019
Definition at line 10 of file sensor.c.
Referenced by Button_ISR(), and MPU_ISR().
pk
struct tx_packet pk
Definition at line 11 of file sensor.c.
Referenced by Button_ISR(), and MPU_ISR().