button.c File Reference
#include `Include/button.h`
Functions
void ConfigureButton ()
Configure On board user button on PJ0.
void Button_ISR (void)
Button click.
Function Documentation
Button_ISR()
void Button_ISR (void)
Button click.
Definition at line 25 of file button.c.
References button_flag, and pk.
Referenced by ConfigureButton().
ConfigureButton()
void ConfigureButton ()
Configure On board user button on PJ0.
File: button.c Author: Vatsal Sheth & Sarthak Jain Description: This file contains configuration and isr for user button Date: 4/29/2019
Definition at line 12 of file button.c.
References Button_ISR().
Referenced by Sensor_fn().