gps_driver.c File Reference
#include `Include/gps_driver.h`
Macros
#define COMBINE(sentence_type, term_number) (((unsigned)(sentence_type) << 5) | term_number)
Functions
boole gpsisdigit (char c)
long altitude ()
unsigned long course ()
unsigned long speed ()
unsigned short gps_satellites ()
unsigned long gps_hdop ()
clock_t uptime ()
float radians (float deg)
float degrees (float rad)
boole gps_encode (char c)
void gps_stats (unsigned long *chars, unsigned short *sentences, unsigned short *failed_cs)
int from_hex (char a)
unsigned long gps_parse_decimal ()
unsigned long gps_parse_degrees ()
boole gps_term_complete ()
Processes a just-completed term.
long gpsatol (const char *str)
int gpsstrcmp (const char *str1, const char *str2)
float gps_distance_between (float lat1, float long1, float lat2, float long2)
float gps_course_to (float lat1, float long1, float lat2, float long2)
const char * gps_cardinal (float course)
void gps_get_position (long *latitude, long *longitude, unsigned long *fix_age)
lat/long in hundred thousandth of a degree and age of fix in milliseconds
void gps_get_datetime (unsigned long *date, unsigned long *time, unsigned long *age)
Date as ddmmyy, time as hhmmsscc, and age in milliseconds.
void gps_f_get_position (float *latitude, float *longitude, unsigned long *fix_age)
void gps_crack_datetime (int *year, byte *month, byte *day, byte *hour, byte *minute, byte *second, byte *hundredths, unsigned long *age)
float gps_f_altitude ()
float gps_f_course ()
float gps_f_speed_knots ()
float gps_f_speed_mph ()
float gps_f_speed_mps ()
float gps_f_speed_kmph ()
Variables
unsigned long _time
unsigned long _new_time
unsigned long _date
unsigned long _new_date
long _latitude
long _new_latitude
long _longitude
long _new_longitude
long _altitude
long _new_altitude
unsigned long _speed
unsigned long _new_speed
unsigned long _course
unsigned long _new_course
unsigned long _hdop
unsigned long _new_hdop
unsigned short _numsats
unsigned short _new_numsats
unsigned long _last_time_fix
unsigned long _new_time_fix
unsigned long _last_position_fix
unsigned long _new_position_fix
byte _parity
boole _is_checksum_term
char _term [15]
byte _sentence_type
byte _term_number = 0
byte _term_offset = 0
boole _is_gps_data_good
unsigned long _encoded_characters
unsigned short _good_sentences
unsigned short _failed_checksum
unsigned short _passed_checksum
Macro Definition Documentation
COMBINE
#define COMBINE(sentence_type, term_number) (((unsigned)(sentence_type) << 5) | term_number)
Definition at line 251 of file gps_driver.c.
Referenced by gps_term_complete().
Function Documentation
altitude()
long altitude () [inline]
Definition at line 69 of file gps_driver.c.
References _altitude.
course()
unsigned long course () [inline]
Definition at line 72 of file gps_driver.c.
References _course.
Referenced by library_version().
degrees()
float degrees (float rad)
Parameters
rad
Returns
Definition at line 104 of file gps_driver.c.
References PI.
Referenced by gps_course_to().
from_hex()
int from_hex (char a)
Parameters
a
Returns
Definition at line 184 of file gps_driver.c.
Referenced by gps_term_complete().
gps_cardinal()
const char* gps_cardinal (float course)
Parameters
course
Returns
Definition at line 463 of file gps_driver.c.
Referenced by library_version().
gps_course_to()
float gps_course_to (float lat1, float long1, float lat2, float long2)
Parameters
lat1
long1
lat2
long2
Returns
Definition at line 438 of file gps_driver.c.
References degrees(), radians(), and TWO_PI.
Referenced by Actuator_fn(), and library_version().
gps_crack_datetime()
void gps_crack_datetime (int * year, byte * month, byte * day, byte * hour, byte * minute, byte * second, byte * hundredths, unsigned long * age)
Parameters
year
month
day
hour
minute
second
hundredths
age
Definition at line 531 of file gps_driver.c.
References gps_get_datetime().
gps_distance_between()
float gps_distance_between (float lat1, float long1, float lat2, float long2)
Parameters
lat1
long1
lat2
long2
Returns
Definition at line 405 of file gps_driver.c.
References radians(), and sq.
Referenced by library_version().
gps_encode()
boole gps_encode (char c)
Parameters
c
Returns
Definition at line 114 of file gps_driver.c.
References _encoded_characters, _is_checksum_term, _is_gps_data_good, _parity, _sentence_type, _term, _term_number, _term_offset, GPS_SENTENCE_OTHER, and gps_term_complete().
Referenced by Sensor_fn().
gps_f_altitude()
float gps_f_altitude ()
Returns
Definition at line 553 of file gps_driver.c.
References _altitude, GPS_INVALID_ALTITUDE, and GPS_INVALID_F_ALTITUDE.
gps_f_course()
float gps_f_course ()
Returns
Definition at line 562 of file gps_driver.c.
References _course, GPS_INVALID_ANGLE, and GPS_INVALID_F_ANGLE.
gps_f_get_position()
void gps_f_get_position (float * latitude, float * longitude, unsigned long * fix_age)
Parameters
latitude
longitude
fix_age
Definition at line 512 of file gps_driver.c.
References gps_get_position(), GPS_INVALID_ANGLE, and GPS_INVALID_F_ANGLE.
Referenced by Sensor_fn().
gps_f_speed_kmph()
float gps_f_speed_kmph ()
Returns
Definition at line 600 of file gps_driver.c.
References gps_f_speed_knots(), GPS_INVALID_F_SPEED, and GPS_KMPH_PER_KNOT.
gps_f_speed_knots()
float gps_f_speed_knots ()
Returns
Definition at line 571 of file gps_driver.c.
References _speed, GPS_INVALID_F_SPEED, and GPS_INVALID_SPEED.
Referenced by gps_f_speed_kmph(), gps_f_speed_mph(), and gps_f_speed_mps().
gps_f_speed_mph()
float gps_f_speed_mph ()
Returns
Definition at line 580 of file gps_driver.c.
References gps_f_speed_knots(), GPS_INVALID_F_SPEED, and GPS_MPH_PER_KNOT.
gps_f_speed_mps()
float gps_f_speed_mps ()
Returns
Definition at line 590 of file gps_driver.c.
References gps_f_speed_knots(), GPS_INVALID_F_SPEED, and GPS_MPS_PER_KNOT.
gps_get_datetime()
void gps_get_datetime (unsigned long * date, unsigned long * time, unsigned long * age)
Date as ddmmyy, time as hhmmsscc, and age in milliseconds.
Parameters
date Pointer to return date value
time Pointer to return time value
age Pointer to return age value
Definition at line 495 of file gps_driver.c.
References _date, _last_time_fix, _time, GPS_INVALID_AGE, GPS_INVALID_FIX_TIME, and uptime().
Referenced by gps_crack_datetime().
gps_get_position()
void gps_get_position (long * latitude, long * longitude, unsigned long * fix_age)
lat/long in hundred thousandth of a degree and age of fix in milliseconds
Parameters
latitude Pointer to write latitude value
longitude Pointer to write longitude value
fix_age
Definition at line 477 of file gps_driver.c.
References _last_position_fix, _latitude, _longitude, GPS_INVALID_AGE, GPS_INVALID_FIX_TIME, and uptime().
Referenced by gps_f_get_position().
gps_hdop()
unsigned long gps_hdop (void) [inline]
Definition at line 81 of file gps_driver.c.
References _hdop.
gps_parse_decimal()
unsigned long gps_parse_decimal ()
Definition at line 197 of file gps_driver.c.
References _term, gpsatol(), and gpsisdigit().
Referenced by gps_term_complete().
gps_parse_degrees()
unsigned long gps_parse_degrees ()
Definition at line 228 of file gps_driver.c.
References _term, gpsatol(), and gpsisdigit().
Referenced by gps_term_complete().
gps_satellites()
unsigned short gps_satellites (void) [inline]
Definition at line 78 of file gps_driver.c.
References _numsats.
Referenced by Sensor_fn().
gps_stats()
void gps_stats (unsigned long * chars, unsigned short * sentences, unsigned short * failed_cs)
Parameters
chars
sentences
failed_cs
Definition at line 164 of file gps_driver.c.
References _encoded_characters, _failed_checksum, and _good_sentences.
Referenced by library_version().
gps_term_complete()
boole gps_term_complete ()
Processes a just-completed term.
Returns
Returns true if new sentence has just passed checksum test and is validated
Definition at line 257 of file gps_driver.c.
References _altitude, _course, _date, _failed_checksum, _good_sentences, _hdop, _is_checksum_term, _is_gps_data_good, _last_position_fix, _last_time_fix, _latitude, _longitude, _new_altitude, _new_course, _new_date, _new_hdop, _new_latitude, _new_longitude, _new_numsats, _new_position_fix, _new_speed, _new_time, _new_time_fix, _numsats, _parity, _sentence_type, _speed, _term, _term_number, _time, COMBINE, from_hex(), GPGGA_TERM, GPRMC_TERM, gps_parse_decimal(), gps_parse_degrees(), GPS_SENTENCE_GPGGA, GPS_SENTENCE_GPRMC, GPS_SENTENCE_OTHER, gpsatol(), gpsstrcmp(), and uptime().
Referenced by gps_encode().
gpsatol()
long gpsatol (const char * str)
Parameters
str
Definition at line 376 of file gps_driver.c.
References gpsisdigit().
Referenced by gps_parse_decimal(), gps_parse_degrees(), and gps_term_complete().
gpsisdigit()
boole gpsisdigit (char c)
Definition at line 66 of file gps_driver.c.
Referenced by gps_parse_decimal(), gps_parse_degrees(), and gpsatol().
gpsstrcmp()
int gpsstrcmp (const char * str1, const char * str2)
Parameters
str1
str2
Returns
Definition at line 390 of file gps_driver.c.
Referenced by gps_term_complete().
radians()
float radians (float deg)
Parameters
deg
Returns
Definition at line 94 of file gps_driver.c.
References PI.
Referenced by gps_course_to(), and gps_distance_between().
speed()
unsigned long speed () [inline]
Definition at line 75 of file gps_driver.c.
References _speed.
uptime()
clock_t uptime ()
Definition at line 84 of file gps_driver.c.
Referenced by gps_get_datetime(), gps_get_position(), and gps_term_complete().
Variable Documentation
_altitude
long _altitude
Definition at line 35 of file gps_driver.c.
Referenced by altitude(), gps_f_altitude(), and gps_term_complete().
_course
unsigned long _course
Definition at line 37 of file gps_driver.c.
Referenced by course(), gps_f_course(), and gps_term_complete().
_date
unsigned long _date
Definition at line 32 of file gps_driver.c.
Referenced by gps_get_datetime(), and gps_term_complete().
_encoded_characters
unsigned long _encoded_characters
Definition at line 55 of file gps_driver.c.
Referenced by gps_encode(), and gps_stats().
_failed_checksum
unsigned short _failed_checksum
Definition at line 57 of file gps_driver.c.
Referenced by gps_stats(), and gps_term_complete().
_good_sentences
unsigned short _good_sentences
Definition at line 56 of file gps_driver.c.
Referenced by gps_stats(), and gps_term_complete().
_hdop
unsigned long _hdop
Definition at line 38 of file gps_driver.c.
Referenced by gps_hdop(), and gps_term_complete().
_is_checksum_term
boole _is_checksum_term
Definition at line 46 of file gps_driver.c.
Referenced by gps_encode(), and gps_term_complete().
_is_gps_data_good
boole _is_gps_data_good
Definition at line 51 of file gps_driver.c.
Referenced by gps_encode(), and gps_term_complete().
_last_position_fix
unsigned long _last_position_fix
Definition at line 42 of file gps_driver.c.
Referenced by gps_get_position(), and gps_term_complete().
_last_time_fix
unsigned long _last_time_fix
Definition at line 41 of file gps_driver.c.
Referenced by gps_get_datetime(), and gps_term_complete().
_latitude
long _latitude
Definition at line 33 of file gps_driver.c.
Referenced by gps_get_position(), and gps_term_complete().
_longitude
long _longitude
Definition at line 34 of file gps_driver.c.
Referenced by gps_get_position(), and gps_term_complete().
_new_altitude
long _new_altitude
Definition at line 35 of file gps_driver.c.
Referenced by gps_term_complete().
_new_course
unsigned long _new_course
Definition at line 37 of file gps_driver.c.
Referenced by gps_term_complete().
_new_date
unsigned long _new_date
Definition at line 32 of file gps_driver.c.
Referenced by gps_term_complete().
_new_hdop
unsigned long _new_hdop
Definition at line 38 of file gps_driver.c.
Referenced by gps_term_complete().
_new_latitude
long _new_latitude
Definition at line 33 of file gps_driver.c.
Referenced by gps_term_complete().
_new_longitude
long _new_longitude
Definition at line 34 of file gps_driver.c.
Referenced by gps_term_complete().
_new_numsats
unsigned short _new_numsats
Definition at line 39 of file gps_driver.c.
Referenced by gps_term_complete().
_new_position_fix
unsigned long _new_position_fix
Definition at line 42 of file gps_driver.c.
Referenced by gps_term_complete().
_new_speed
unsigned long _new_speed
Definition at line 36 of file gps_driver.c.
Referenced by gps_term_complete().
_new_time
unsigned long _new_time
Definition at line 31 of file gps_driver.c.
Referenced by gps_term_complete().
_new_time_fix
unsigned long _new_time_fix
Definition at line 41 of file gps_driver.c.
Referenced by gps_term_complete().
_numsats
unsigned short _numsats
Definition at line 39 of file gps_driver.c.
Referenced by gps_satellites(), and gps_term_complete().
_parity
byte _parity
Definition at line 45 of file gps_driver.c.
Referenced by gps_encode(), and gps_term_complete().
_passed_checksum
unsigned short _passed_checksum
Definition at line 58 of file gps_driver.c.
_sentence_type
byte _sentence_type
Definition at line 48 of file gps_driver.c.
Referenced by gps_encode(), and gps_term_complete().
_speed
unsigned long _speed
Definition at line 36 of file gps_driver.c.
Referenced by gps_f_speed_knots(), gps_term_complete(), and speed().
_term
char _term[15]
Definition at line 47 of file gps_driver.c.
Referenced by gps_encode(), gps_parse_decimal(), gps_parse_degrees(), and gps_term_complete().
_term_number
byte _term_number = 0
Definition at line 49 of file gps_driver.c.
Referenced by gps_encode(), and gps_term_complete().
_term_offset
byte _term_offset = 0
Definition at line 50 of file gps_driver.c.
Referenced by gps_encode().
_time
unsigned long _time
File: gps_driver.c Author: Vatsal Sheth & Sarthak Jain Description: This file has API for GPS Date: 4/29/2019 Reference: Arduino TinyGPS C++ Library
Definition at line 31 of file gps_driver.c.
Referenced by gps_get_datetime(), and gps_term_complete().