Include/gps_driver.h File Reference
#include <math.h>
#include <time.h>
#include `basic.h`
Macros
#define false 0
#define true 1
#define PI 3.14159265
#define TWO_PI 2*PI
#define sq(x) ((x)*(x))
#define GPRMC_TERM `GPRMC`
#define GPGGA_TERM `GPGGA`
#define GPS_INVALID_F_ANGLE 1000.0
#define GPS_INVALID_F_ALTITUDE 1000000.0
#define GPS_INVALID_F_SPEED -1.0
#define GPS_VERSION 12
#define GPS_MPH_PER_KNOT 1.15077945
#define GPS_MPS_PER_KNOT 0.51444444
#define GPS_KMPH_PER_KNOT 1.852
#define GPS_MILES_PER_METER 0.00062137112
#define GPS_KM_PER_METER 0.001
Typedefs
typedef char boole
typedef unsigned char byte
Enumerations
enum {
GPS_INVALID_AGE = 0xFFFFFFFF,
GPS_INVALID_ANGLE = 999999999,
GPS_INVALID_ALTITUDE = 999999999,
GPS_INVALID_DATE = 0,
GPS_INVALID_TIME = 0xFFFFFFFF,
GPS_INVALID_SPEED = 999999999,
GPS_INVALID_FIX_TIME = 0xFFFFFFFF,
GPS_INVALID_SATELLITES = 0xFF,
GPS_INVALID_HDOP = 0xFFFFFFFF
 }
enum { GPS_SENTENCE_GPGGA,
GPS_SENTENCE_GPRMC,
GPS_SENTENCE_OTHER
 }
Functions
boole encode (char c)
void gps_get_position (long *latitude, long *longitude, unsigned long *fix_age)
lat/long in hundred thousandth of a degree and age of fix in milliseconds
void gps_get_datetime (unsigned long *date, unsigned long *time, unsigned long *age)
Date as ddmmyy, time as hhmmsscc, and age in milliseconds.
unsigned short gps_satellites (void)
unsigned long gps_hdop (void)
boole gps_encode (char)
void gps_f_get_position (float *latitude, float *longitude, unsigned long *fix_age)
void gps_crack_datetime (int *year, byte *month, byte *day, byte *hour, byte *minute, byte *second, byte *hundredths, unsigned long *fix_age)
float gps_f_altitude ()
float gps_f_course ()
float gps_f_speed_knots ()
float gps_f_speed_mph ()
float gps_f_speed_mps ()
float gps_f_speed_kmph ()
static int library_version ()
static float gps_distance_between (float lat1, float long1, float lat2, float long2)
float gps_course_to (float lat1, float long1, float lat2, float long2)
static const char * gps_cardinal (float course)
void gps_stats (unsigned long *chars, unsigned short *good_sentences, unsigned short *failed_cs)
int from_hex (char a)
unsigned long gps_parse_decimal ()
unsigned long gps_parse_degrees ()
boole gps_term_complete ()
Processes a just-completed term.
boole gpsisdigit (char c)
long gpsatol (const char *str)
int gpsstrcmp (const char *str1, const char *str2)
Macro Definition Documentation
false
#define false 0
Definition at line 20 of file gps_driver.h.
GPGGA_TERM
#define GPGGA_TERM `GPGGA`
Definition at line 29 of file gps_driver.h.
Referenced by gps_term_complete().
GPRMC_TERM
#define GPRMC_TERM `GPRMC`
Definition at line 28 of file gps_driver.h.
Referenced by gps_term_complete().
GPS_INVALID_F_ALTITUDE
#define GPS_INVALID_F_ALTITUDE 1000000.0
Definition at line 32 of file gps_driver.h.
Referenced by gps_f_altitude().
GPS_INVALID_F_ANGLE
#define GPS_INVALID_F_ANGLE 1000.0
Definition at line 31 of file gps_driver.h.
Referenced by gps_f_course(), and gps_f_get_position().
GPS_INVALID_F_SPEED
#define GPS_INVALID_F_SPEED -1.0
Definition at line 33 of file gps_driver.h.
Referenced by gps_f_speed_kmph(), gps_f_speed_knots(), gps_f_speed_mph(), and gps_f_speed_mps().
GPS_KM_PER_METER
#define GPS_KM_PER_METER 0.001
Definition at line 41 of file gps_driver.h.
GPS_KMPH_PER_KNOT
#define GPS_KMPH_PER_KNOT 1.852
Definition at line 39 of file gps_driver.h.
Referenced by gps_f_speed_kmph().
GPS_MILES_PER_METER
#define GPS_MILES_PER_METER 0.00062137112
Definition at line 40 of file gps_driver.h.
GPS_MPH_PER_KNOT
#define GPS_MPH_PER_KNOT 1.15077945
Definition at line 37 of file gps_driver.h.
Referenced by gps_f_speed_mph().
GPS_MPS_PER_KNOT
#define GPS_MPS_PER_KNOT 0.51444444
Definition at line 38 of file gps_driver.h.
Referenced by gps_f_speed_mps().
GPS_VERSION
#define GPS_VERSION 12
Definition at line 36 of file gps_driver.h.
Referenced by library_version().
PI
#define PI 3.14159265
Definition at line 23 of file gps_driver.h.
Referenced by degrees(), and radians().
sq
#define sq(x) ((x)*(x))
Definition at line 26 of file gps_driver.h.
Referenced by gps_distance_between().
true
#define true 1
Definition at line 21 of file gps_driver.h.
TWO_PI
#define TWO_PI 2*PI
Definition at line 24 of file gps_driver.h.
Referenced by gps_course_to().
Typedef Documentation
boole
typedef char boole
File: gps_driver.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by gps_driver.c Date: 4/29/2019 Reference: Arduino TinyGPS C++ library
Definition at line 18 of file gps_driver.h.
byte
typedef unsigned char byte
Definition at line 19 of file gps_driver.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GPS_INVALID_AGE
GPS_INVALID_ANGLE
GPS_INVALID_ALTITUDE
GPS_INVALID_DATE
GPS_INVALID_TIME
GPS_INVALID_SPEED
GPS_INVALID_FIX_TIME
GPS_INVALID_SATELLITES
GPS_INVALID_HDOP
Definition at line 45 of file gps_driver.h.
anonymous enum
anonymous enum
Enumerator
GPS_SENTENCE_GPGGA
GPS_SENTENCE_GPRMC
GPS_SENTENCE_OTHER
Definition at line 95 of file gps_driver.h.
Function Documentation
encode()
boole encode (char c)
from_hex()
int from_hex (char a)
Parameters
a
Returns
Definition at line 184 of file gps_driver.c.
Referenced by gps_term_complete().
gps_cardinal()
static const char* gps_cardinal (float course) [static]
Parameters
course
Returns
Definition at line 463 of file gps_driver.c.
Referenced by library_version().
gps_course_to()
float gps_course_to (float lat1, float long1, float lat2, float long2)
Parameters
lat1
long1
lat2
long2
Returns
Definition at line 438 of file gps_driver.c.
References degrees(), radians(), and TWO_PI.
Referenced by library_version().
gps_crack_datetime()
void gps_crack_datetime (int * year, byte * month, byte * day, byte * hour, byte * minute, byte * second, byte * hundredths, unsigned long * age)
Parameters
year
month
day
hour
minute
second
hundredths
age
Definition at line 531 of file gps_driver.c.
References gps_get_datetime().
gps_distance_between()
static float gps_distance_between (float lat1, float long1, float lat2, float long2) [static]
Parameters
lat1
long1
lat2
long2
Returns
Definition at line 405 of file gps_driver.c.
References radians(), and sq.
Referenced by library_version().
gps_encode()
boole gps_encode (char c)
Parameters
c
Returns
Definition at line 114 of file gps_driver.c.
References _encoded_characters, _is_checksum_term, _is_gps_data_good, _parity, _sentence_type, _term, _term_number, _term_offset, GPS_SENTENCE_OTHER, and gps_term_complete().
Referenced by Sensor_fn().
gps_f_altitude()
float gps_f_altitude ()
Returns
Definition at line 553 of file gps_driver.c.
References _altitude, GPS_INVALID_ALTITUDE, and GPS_INVALID_F_ALTITUDE.
gps_f_course()
float gps_f_course ()
Returns
Definition at line 562 of file gps_driver.c.
References _course, GPS_INVALID_ANGLE, and GPS_INVALID_F_ANGLE.
gps_f_get_position()
void gps_f_get_position (float * latitude, float * longitude, unsigned long * fix_age)
Parameters
latitude
longitude
fix_age
Definition at line 512 of file gps_driver.c.
References gps_get_position(), GPS_INVALID_ANGLE, and GPS_INVALID_F_ANGLE.
Referenced by Sensor_fn().
gps_f_speed_kmph()
float gps_f_speed_kmph ()
Returns
Definition at line 600 of file gps_driver.c.
References gps_f_speed_knots(), GPS_INVALID_F_SPEED, and GPS_KMPH_PER_KNOT.
gps_f_speed_knots()
float gps_f_speed_knots ()
Returns
Definition at line 571 of file gps_driver.c.
References _speed, GPS_INVALID_F_SPEED, and GPS_INVALID_SPEED.
Referenced by gps_f_speed_kmph(), gps_f_speed_mph(), and gps_f_speed_mps().
gps_f_speed_mph()
float gps_f_speed_mph ()
Returns
Definition at line 580 of file gps_driver.c.
References gps_f_speed_knots(), GPS_INVALID_F_SPEED, and GPS_MPH_PER_KNOT.
gps_f_speed_mps()
float gps_f_speed_mps ()
Returns
Definition at line 590 of file gps_driver.c.
References gps_f_speed_knots(), GPS_INVALID_F_SPEED, and GPS_MPS_PER_KNOT.
gps_get_datetime()
void gps_get_datetime (unsigned long * date, unsigned long * time, unsigned long * age)
Date as ddmmyy, time as hhmmsscc, and age in milliseconds.
Parameters
date Pointer to return date value
time Pointer to return time value
age Pointer to return age value
Definition at line 495 of file gps_driver.c.
References _date, _last_time_fix, _time, GPS_INVALID_AGE, GPS_INVALID_FIX_TIME, and uptime().
Referenced by gps_crack_datetime().
gps_get_position()
void gps_get_position (long * latitude, long * longitude, unsigned long * fix_age)
lat/long in hundred thousandth of a degree and age of fix in milliseconds
Parameters
latitude Pointer to write latitude value
longitude Pointer to write longitude value
fix_age
Definition at line 477 of file gps_driver.c.
References _last_position_fix, _latitude, _longitude, GPS_INVALID_AGE, GPS_INVALID_FIX_TIME, and uptime().
Referenced by gps_f_get_position().
gps_hdop()
unsigned long gps_hdop (void) [inline]
Definition at line 81 of file gps_driver.c.
References _hdop.
gps_parse_decimal()
unsigned long gps_parse_decimal ()
Definition at line 197 of file gps_driver.c.
References _term, gpsatol(), and gpsisdigit().
Referenced by gps_term_complete().
gps_parse_degrees()
unsigned long gps_parse_degrees ()
Definition at line 228 of file gps_driver.c.
References _term, gpsatol(), and gpsisdigit().
Referenced by gps_term_complete().
gps_satellites()
unsigned short gps_satellites (void) [inline]
Definition at line 78 of file gps_driver.c.
References _numsats.
Referenced by Sensor_fn().
gps_stats()
void gps_stats (unsigned long * chars, unsigned short * sentences, unsigned short * failed_cs)
Parameters
chars
sentences
failed_cs
Definition at line 164 of file gps_driver.c.
References _encoded_characters, _failed_checksum, and _good_sentences.
Referenced by library_version().
gps_term_complete()
boole gps_term_complete ()
Processes a just-completed term.
Returns
Returns true if new sentence has just passed checksum test and is validated
Definition at line 257 of file gps_driver.c.
References _altitude, _course, _date, _failed_checksum, _good_sentences, _hdop, _is_checksum_term, _is_gps_data_good, _last_position_fix, _last_time_fix, _latitude, _longitude, _new_altitude, _new_course, _new_date, _new_hdop, _new_latitude, _new_longitude, _new_numsats, _new_position_fix, _new_speed, _new_time, _new_time_fix, _numsats, _parity, _sentence_type, _speed, _term, _term_number, _time, COMBINE, from_hex(), GPGGA_TERM, GPRMC_TERM, gps_parse_decimal(), gps_parse_degrees(), GPS_SENTENCE_GPGGA, GPS_SENTENCE_GPRMC, GPS_SENTENCE_OTHER, gpsatol(), gpsstrcmp(), and uptime().
Referenced by gps_encode().
gpsatol()
long gpsatol (const char * str)
Parameters
str
Definition at line 376 of file gps_driver.c.
References gpsisdigit().
Referenced by gps_parse_decimal(), gps_parse_degrees(), and gps_term_complete().
gpsisdigit()
boole gpsisdigit (char c)
Definition at line 66 of file gps_driver.c.
Referenced by gps_parse_decimal(), gps_parse_degrees(), and gpsatol().
gpsstrcmp()
int gpsstrcmp (const char * str1, const char * str2)
Parameters
str1
str2
Returns
Definition at line 390 of file gps_driver.c.
Referenced by gps_term_complete().
library_version()
static int library_version () [static]
Definition at line 85 of file gps_driver.h.
References course(), gps_cardinal(), gps_course_to(), gps_distance_between(), gps_stats(), and GPS_VERSION.