i2c_driver.c File Reference
#include `Include/i2c_driver.h`
Functions
void ConfigureI2C2 (void)
Configures I2C 2 Block.
void I2Csend (uint8_t addr, uint8_t *data, uint8_t count)
Writes data on I2C 2 Block.
void I2Creceive (uint8_t addr, uint8_t reg, uint8_t *data, uint8_t count)
Receives specified bytes of data from given register through I2C 2 Block.
Function Documentation
ConfigureI2C2()
void ConfigureI2C2 (void)
Configures I2C 2 Block.
File: i2c_driver.c Author: Vatsal Sheth & Sarthak Jain Description: This file has driver API for I2C Date: 4/29/2019
Definition at line 13 of file i2c_driver.c.
Referenced by ConfigureMPU().
I2Creceive()
void I2Creceive (uint8_t addr, uint8_t reg, uint8_t * data, uint8_t count)
Receives specified bytes of data from given register through I2C 2 Block.
Parameters
addr Slave address
reg Register to read data from
data Pointer to received data
count Number of bytes to be received
Definition at line 84 of file i2c_driver.c.
Referenced by BIST_mpu(), ConfigureMPU(), and MPU_ISR().
I2Csend()
void I2Csend (uint8_t addr, uint8_t * data, uint8_t count)
Writes data on I2C 2 Block.
Parameters
addr Slave addrres
data Pointer to data to be sent
count Number of bytes to be sent from data pointer
Definition at line 45 of file i2c_driver.c.
Referenced by ConfigureMPU().