Include/lcd_driver.h File Reference
#include `basic.h`
Macros
#define data_gpio_base GPIO_PORTM_BASE
#define ctrl_gpio_base GPIO_PORTF_BASE
#define EN GPIO_PIN_1
#define RS GPIO_PIN_2
#define RW GPIO_PIN_3
Functions
void ConfigureLCD (void)
Configure GPIO port M for data and port F for control signals of LCD. LCD initialization steps.
void WR_CMD (uint8_t data)
Write to instruction register of LCD.
uint8_t RD_CMD (void)
Read from instruction register of LCD.
void WR_DATA (uint8_t data)
Write to data register of LCD.
uint8_t RD_DATA (void)
Read from data register of LCD.
void lcdbusywait ()
Polls the LCD busy flag. Function does not return until the LCD controller is ready to accept another command.
void lcdgotoaddr (uint8_t addr)
Sets the cursor to the specified LCD DDRAM address. Should call lcdbusywait().
void lcdgotoxy (uint8_t row, uint8_t column)
Sets the cursor to the LCD DDRAM address corresponding to the specified row and column. Location (0,0) is the top left corner of the LCD screen.
void lcdputch (char cc)
Writes the specified character to the current.
void lcdputstr (char *ss)
Writes the specified null-terminated string to the LCD starting at the current LCD cursor position. Automatically wraps long strings to the next LCD line after the right edge of the display screen has been reached.
void lcdcreatechar (uint8_t ccode, uint8_t row_vals[8])
Function to create a 5x8 pixel custom character with character code ccode (0<=ccode<=7) using the row values given in the 8-byte array row_vals[].
void lcdclear ()
Clears the LCD using the HD44780 Clear display instruction.
void lcdputfloat (float a)
Displays float number upto 4 decimal points.
void lcdputint (int a)
Displays integer number upto 3 decimal.
Variables
uint8_t row_addr [4]
Macro Definition Documentation
ctrl_gpio_base
#define ctrl_gpio_base GPIO_PORTF_BASE
Definition at line 21 of file lcd_driver.h.
Referenced by ConfigureLCD(), RD_CMD(), RD_DATA(), WR_CMD(), and WR_DATA().
data_gpio_base
#define data_gpio_base GPIO_PORTM_BASE
File: lcd_driver.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by lcd_driver.c Date: 4/29/2019
Definition at line 20 of file lcd_driver.h.
Referenced by ConfigureLCD(), RD_CMD(), RD_DATA(), WR_CMD(), and WR_DATA().
EN
#define EN GPIO_PIN_1
Definition at line 23 of file lcd_driver.h.
Referenced by ConfigureLCD(), RD_CMD(), RD_DATA(), WR_CMD(), and WR_DATA().
RS
#define RS GPIO_PIN_2
Definition at line 24 of file lcd_driver.h.
Referenced by ConfigureLCD(), RD_CMD(), RD_DATA(), WR_CMD(), and WR_DATA().
RW
#define RW GPIO_PIN_3
Definition at line 25 of file lcd_driver.h.
Referenced by ConfigureLCD(), RD_CMD(), RD_DATA(), WR_CMD(), and WR_DATA().
Function Documentation
ConfigureLCD()
void ConfigureLCD (void)
Configure GPIO port M for data and port F for control signals of LCD. LCD initialization steps.
Definition at line 90 of file lcd_driver.c.
References ctrl_gpio_base, data_gpio_base, EN, lcdbusywait(), lcdclear(), RS, RW, and WR_CMD().
Referenced by Actuator_fn().
lcdbusywait()
void lcdbusywait ()
Polls the LCD busy flag. Function does not return until the LCD controller is ready to accept another command.
Definition at line 114 of file lcd_driver.c.
References RD_CMD().
Referenced by ConfigureLCD(), lcdclear(), lcdcreatechar(), lcdgotoaddr(), and lcdputch().
lcdclear()
void lcdclear ()
Clears the LCD using the HD44780 Clear display instruction.
Definition at line 265 of file lcd_driver.c.
References lcdbusywait(), and WR_CMD().
Referenced by ConfigureLCD().
lcdcreatechar()
void lcdcreatechar (uint8_t ccode, uint8_t row_vals[8])
Function to create a 5x8 pixel custom character with character code ccode (0<=ccode<=7) using the row values given in the 8-byte array row_vals[].
Parameters
ccode Character code 0-7
row_vals Array of row values to generate character. Bit value 1 represents dark pixel.
Definition at line 249 of file lcd_driver.c.
References lcdbusywait(), WR_CMD(), and WR_DATA().
lcdgotoaddr()
void lcdgotoaddr (uint8_t addr)
Sets the cursor to the specified LCD DDRAM address. Should call lcdbusywait().
Parameters
addr DDRAM address to set cursor
Definition at line 129 of file lcd_driver.c.
References lcdbusywait(), and WR_CMD().
Referenced by Actuator_fn(), lcdgotoxy(), and lcdputstr().
lcdgotoxy()
void lcdgotoxy (uint8_t row, uint8_t column)
Sets the cursor to the LCD DDRAM address corresponding to the specified row and column. Location (0,0) is the top left corner of the LCD screen.
Parameters
row Line number 0-3
column Column number 0-15
Definition at line 140 of file lcd_driver.c.
References lcdgotoaddr(), and row_addr.
lcdputch()
void lcdputch (char cc)
Writes the specified character to the current.
Parameters
cc Character to be written on LCD
Definition at line 151 of file lcd_driver.c.
References lcdbusywait(), and WR_DATA().
Referenced by Actuator_fn(), lcdputfloat(), lcdputint(), and lcdputstr().
lcdputfloat()
void lcdputfloat (float a)
Displays float number upto 4 decimal points.
Parameters
a Input float number to be displayed
Definition at line 218 of file lcd_driver.c.
References lcdputch(), and lcdputint().
Referenced by Actuator_fn().
lcdputint()
void lcdputint (int a)
Displays integer number upto 3 decimal.
Parameters
a Input integer number to be displayed
Definition at line 196 of file lcd_driver.c.
References lcdputch().
Referenced by Actuator_fn(), and lcdputfloat().
lcdputstr()
void lcdputstr (char * ss)
Writes the specified null-terminated string to the LCD starting at the current LCD cursor position. Automatically wraps long strings to the next LCD line after the right edge of the display screen has been reached.
Parameters
ss String to be displayed on LCD
Definition at line 162 of file lcd_driver.c.
References lcdgotoaddr(), lcdputch(), RD_CMD(), and row_addr.
Referenced by Actuator_fn().
RD_CMD()
uint8_t RD_CMD (void)
Read from instruction register of LCD.
Returns
Instruction register value
Definition at line 35 of file lcd_driver.c.
References ctrl_gpio_base, data_gpio_base, EN, RS, and RW.
Referenced by lcdbusywait(), and lcdputstr().
RD_DATA()
uint8_t RD_DATA (void)
Read from data register of LCD.
Returns
Data register value
Definition at line 72 of file lcd_driver.c.
References ctrl_gpio_base, data_gpio_base, EN, RS, and RW.
WR_CMD()
void WR_CMD (uint8_t data)
Write to instruction register of LCD.
Parameters
data Command to be written in instruction register
Definition at line 17 of file lcd_driver.c.
References ctrl_gpio_base, data_gpio_base, EN, RS, and RW.
Referenced by ConfigureLCD(), lcdclear(), lcdcreatechar(), and lcdgotoaddr().
WR_DATA()
void WR_DATA (uint8_t data)
Write to data register of LCD.
Parameters
data Value to be written in data register
Definition at line 54 of file lcd_driver.c.
References ctrl_gpio_base, data_gpio_base, EN, RS, and RW.
Referenced by lcdcreatechar(), and lcdputch().
Variable Documentation
row_addr
uint8_t row_addr[4]
File: lcd_driver.c Author: Vatsal Sheth & Sarthak Jain Description: This file has driver API for 16x2 character LCD Date: 4/29/2019
Definition at line 11 of file lcd_driver.c.
Referenced by lcdgotoxy(), and lcdputstr().