main.c File Reference
#include `Include/main.h`
Functions
void vApplicationStackOverflowHook (xTaskHandle *pxTask, char *pcTaskName)
int main (void)
Variables
volatile unsigned long g_vulRunTimeStatsCountValue
Function Documentation
main()
int main (void)
Definition at line 49 of file main.c.
References ConfigureButton(), ConfigureNRF(), ConfigureUART(), and g_ui32SysClock.
vApplicationStackOverflowHook()
void vApplicationStackOverflowHook (xTaskHandle * pxTask, char * pcTaskName)
Definition at line 32 of file main.c.
Variable Documentation
g_vulRunTimeStatsCountValue
volatile unsigned long g_vulRunTimeStatsCountValue
File: main.c Author: Vatsal Sheth Description: Date: 4/29/2019 Refrence: Tivaware demo codes
Definition at line 11 of file main.c.