mpu6050.c File Reference
#include `Include/mpu6050.h`
Functions
uint8_t ConfigureMPU (void)
Configure I2C 2 block and Gpio pin for interrupt from MPU6050. Writes initialization registers in MPU and configures DMP engine.
uint8_t BIST_mpu ()
Reads the WHO AM I register on MPU6050 to verify the identity.
void MPU_ISR (void)
ISR of MPU6050 module.
Function Documentation
BIST_mpu()
uint8_t BIST_mpu (void)
Reads the WHO AM I register on MPU6050 to verify the identity.
Returns
1 on success and 0 on failure
Definition at line 63 of file mpu6050.c.
References I2Creceive(), and SLAVE_ADDR.
Referenced by ConfigureMPU().
ConfigureMPU()
uint8_t ConfigureMPU (void)
Configure I2C 2 block and Gpio pin for interrupt from MPU6050. Writes initialization registers in MPU and configures DMP engine.
File: mpu6050.c Author: Vatsal Sheth & Sarthak Jain Description: This file has driver API for MPU6050 sensor Date: 4/29/2019
Returns
1 on BIST success and 0 on BIST failure
Definition at line 14 of file mpu6050.c.
References BIST_mpu(), ConfigureI2C2(), I2Creceive(), I2Csend(), mpu_ad0, mpu_gpio_base, mpu_irq, MPU_ISR(), and SLAVE_ADDR.
Referenced by Sensor_fn().
MPU_ISR()
void MPU_ISR (void)
ISR of MPU6050 module.
Definition at line 81 of file mpu6050.c.
References button_flag, I2Creceive(), mpu_gpio_base, pk, SLAVE_ADDR, time_exch_flag, and xSemaphore_s.
Referenced by ConfigureMPU().