Include/mpu6050.h File Reference
#include `basic.h`
#include `i2c_driver.h`
Macros
#define SLAVE_ADDR (0x68)
#define mpu_gpio_base (GPIO_PORTB_BASE)
#define mpu_irq (GPIO_PIN_2)
#define mpu_ad0 (GPIO_PIN_3)
Functions
uint8_t ConfigureMPU (void)
Configure I2C 2 block and Gpio pin for interrupt from MPU6050. Writes initialization registers in MPU and configures DMP engine.
void MPU_ISR (void)
ISR of MPU6050 module.
uint8_t BIST_mpu (void)
Reads the WHO AM I register on MPU6050 to verify the identity.
Variables
uint32_t button_flag
uint32_t time_exch_flag
struct tx_packet pk
SemaphoreHandle_t xSemaphore_s
Macro Definition Documentation
mpu_ad0
#define mpu_ad0 (GPIO_PIN_3)
Definition at line 24 of file mpu6050.h.
Referenced by ConfigureMPU().
mpu_gpio_base
#define mpu_gpio_base (GPIO_PORTB_BASE)
Definition at line 22 of file mpu6050.h.
Referenced by ConfigureMPU(), and MPU_ISR().
mpu_irq
#define mpu_irq (GPIO_PIN_2)
Definition at line 23 of file mpu6050.h.
Referenced by ConfigureMPU().
SLAVE_ADDR
#define SLAVE_ADDR (0x68)
File: mpu6050.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by mpu6050.c Date: 4/29/2019
Definition at line 20 of file mpu6050.h.
Referenced by BIST_mpu(), ConfigureMPU(), and MPU_ISR().
Function Documentation
BIST_mpu()
uint8_t BIST_mpu (void)
Reads the WHO AM I register on MPU6050 to verify the identity.
Returns
1 on success and 0 on failure
Definition at line 63 of file mpu6050.c.
References I2Creceive(), and SLAVE_ADDR.
Referenced by ConfigureMPU().
ConfigureMPU()
uint8_t ConfigureMPU (void)
Configure I2C 2 block and Gpio pin for interrupt from MPU6050. Writes initialization registers in MPU and configures DMP engine.
File: mpu6050.c Author: Vatsal Sheth & Sarthak Jain Description: This file has driver API for MPU6050 sensor Date: 4/29/2019
Returns
1 on BIST success and 0 on BIST failure
Definition at line 14 of file mpu6050.c.
References BIST_mpu(), ConfigureI2C2(), I2Creceive(), I2Csend(), mpu_ad0, mpu_gpio_base, mpu_irq, MPU_ISR(), and SLAVE_ADDR.
Referenced by Sensor_fn().
MPU_ISR()
void MPU_ISR (void)
ISR of MPU6050 module.
Definition at line 81 of file mpu6050.c.
References button_flag, I2Creceive(), mpu_gpio_base, pk, SLAVE_ADDR, time_exch_flag, and xSemaphore_s.
Referenced by ConfigureMPU().
Variable Documentation
button_flag
uint32_t button_flag
File: sensor.c Author: Vatsal Sheth & Sarthak Jain Description: This file creates task for sensors which control GPS, MPU6050, button Date: 4/29/2019
Definition at line 10 of file sensor.c.
pk
struct tx_packet pk
Definition at line 11 of file sensor.c.
time_exch_flag
uint32_t time_exch_flag
Definition at line 10 of file sensor.c.
Referenced by MPU_ISR().
xSemaphore_s
SemaphoreHandle_t xSemaphore_s
Definition at line 13 of file main.c.