Include/nrf24l01.h File Reference
#include `basic.h`
#include `spi_driver.h`
Macros
#define nrf_gpio_base GPIO_PORTL_BASE
#define nrf_csn GPIO_PIN_1
#define nrf_irq GPIO_PIN_2
#define nrf_ce GPIO_PIN_3
#define R_REGISTER(x) (x & 0x1f)
#define W_REGISTER(x) ((x & 0x1f) | 0x20)
#define R_RX_PAYLOAD (0x61)
#define W_TX_PAYLOAD (0xa0)
#define FLUSH_TX (0xe1)
#define FLUSH_RX (0xe2)
#define REUSE_TX_PL (0xe3)
#define R_RX_PL_WID (0x60)
#define W_ACK_PAYLOAD(x) ((x & 0x07) | 0xa8)
#define W_TX_PAYLOAD_NOACK (0xb0)
#define NOP (0xff)
#define CONFIG (0x00)
#define EN_AA (0x01)
#define EN_RXADDR (0x02)
#define SETUP_AW (0x03)
#define SETUP_RETR (0x04)
#define RF_CH (0x05)
#define RF_SETUP (0x06)
#define STATUS (0x07)
#define OBSERVE_TX (0x08)
#define RPD (0x09)
#define RX_ADDR_P(x) (0x0a + x)
#define TX_ADDR (0x10)
#define RX_PW_P(x) (0x11 + x)
#define FIFO_STATUS (0x17)
#define DYNPD (0x1c)
#define FEATURE (0x1d)
Functions
void clear_CSN ()
Clears CSN pin of NRF24l01+ module.
void set_CSN ()
Sets CSN pin of NRF24l01+ module.
void set_CE ()
Sets CE pin of NRF24l01+ module.
void clear_CE ()
Clears CE pin of NRF24l01+ module.
void ConfigureNRF (void)
Configures NRF24l01+ module.
void NRF_ISR (void)
ISR of NRF24l01+ module.
uint8_t NRF_write (uint32_t command, uint8_t *data, uint8_t count)
Write to NRF24l01+ module.
uint8_t NRF_read (uint32_t command, uint8_t *data, uint8_t count)
Read from NRF24l01+ module.
void set_rxmode (void)
Set NRF module to RX mode.
void set_txmode (void)
Set NRF module to TX mode.
Macro Definition Documentation
CONFIG
#define CONFIG (0x00)
Definition at line 33 of file nrf24l01.h.
Referenced by set_rxmode(), and set_txmode().
DYNPD
#define DYNPD (0x1c)
Definition at line 47 of file nrf24l01.h.
EN_AA
#define EN_AA (0x01)
Definition at line 34 of file nrf24l01.h.
EN_RXADDR
#define EN_RXADDR (0x02)
Definition at line 35 of file nrf24l01.h.
Referenced by ConfigureNRF().
FEATURE
#define FEATURE (0x1d)
Definition at line 48 of file nrf24l01.h.
FIFO_STATUS
#define FIFO_STATUS (0x17)
Definition at line 46 of file nrf24l01.h.
Referenced by ConfigureNRF().
FLUSH_RX
#define FLUSH_RX (0xe2)
Definition at line 25 of file nrf24l01.h.
Referenced by ConfigureNRF().
FLUSH_TX
#define FLUSH_TX (0xe1)
Definition at line 24 of file nrf24l01.h.
Referenced by ConfigureNRF().
NOP
#define NOP (0xff)
Definition at line 30 of file nrf24l01.h.
Referenced by ConfigureNRF(), and NRF_read().
nrf_ce
#define nrf_ce GPIO_PIN_3
Definition at line 17 of file nrf24l01.h.
Referenced by clear_CE(), ConfigureNRF(), and set_CE().
nrf_csn
#define nrf_csn GPIO_PIN_1
Definition at line 15 of file nrf24l01.h.
Referenced by clear_CSN(), ConfigureNRF(), and set_CSN().
nrf_gpio_base
#define nrf_gpio_base GPIO_PORTL_BASE
File: nrf24l01.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by nrf24l01.c Date: 4/29/2019
Definition at line 14 of file nrf24l01.h.
Referenced by clear_CE(), clear_CSN(), ConfigureNRF(), NRF_ISR(), set_CE(), and set_CSN().
nrf_irq
#define nrf_irq GPIO_PIN_2
Definition at line 16 of file nrf24l01.h.
Referenced by ConfigureNRF().
OBSERVE_TX
#define OBSERVE_TX (0x08)
Definition at line 41 of file nrf24l01.h.
R_REGISTER
#define R_REGISTER(x) (x & 0x1f)
Definition at line 20 of file nrf24l01.h.
Referenced by ConfigureNRF(), and NRF_ISR().
R_RX_PAYLOAD
#define R_RX_PAYLOAD (0x61)
Definition at line 22 of file nrf24l01.h.
Referenced by Comm_fn().
R_RX_PL_WID
#define R_RX_PL_WID (0x60)
Definition at line 27 of file nrf24l01.h.
REUSE_TX_PL
#define REUSE_TX_PL (0xe3)
Definition at line 26 of file nrf24l01.h.
RF_CH
#define RF_CH (0x05)
Definition at line 38 of file nrf24l01.h.
RF_SETUP
#define RF_SETUP (0x06)
Definition at line 39 of file nrf24l01.h.
RPD
#define RPD (0x09)
Definition at line 42 of file nrf24l01.h.
RX_ADDR_P
#define RX_ADDR_P(x) (0x0a + x)
Definition at line 43 of file nrf24l01.h.
Referenced by ConfigureNRF().
RX_PW_P
#define RX_PW_P(x) (0x11 + x)
Definition at line 45 of file nrf24l01.h.
Referenced by ConfigureNRF().
SETUP_AW
#define SETUP_AW (0x03)
Definition at line 36 of file nrf24l01.h.
SETUP_RETR
#define SETUP_RETR (0x04)
Definition at line 37 of file nrf24l01.h.
STATUS
#define STATUS (0x07)
Definition at line 40 of file nrf24l01.h.
Referenced by NRF_ISR().
TX_ADDR
#define TX_ADDR (0x10)
Definition at line 44 of file nrf24l01.h.
Referenced by ConfigureNRF().
W_ACK_PAYLOAD
#define W_ACK_PAYLOAD(x) ((x & 0x07) | 0xa8)
Definition at line 28 of file nrf24l01.h.
W_REGISTER
#define W_REGISTER(x) ((x & 0x1f) | 0x20)
Definition at line 21 of file nrf24l01.h.
Referenced by ConfigureNRF(), NRF_ISR(), set_rxmode(), and set_txmode().
W_TX_PAYLOAD
#define W_TX_PAYLOAD (0xa0)
Definition at line 23 of file nrf24l01.h.
Referenced by Comm_fn().
W_TX_PAYLOAD_NOACK
#define W_TX_PAYLOAD_NOACK (0xb0)
Definition at line 29 of file nrf24l01.h.
Function Documentation
clear_CE()
void clear_CE ()
Clears CE pin of NRF24l01+ module.
Definition at line 39 of file nrf24l01.c.
References nrf_ce, and nrf_gpio_base.
Referenced by Comm_fn(), NRF_ISR(), and Timer1IntHandler().
clear_CSN()
void clear_CSN ()
Clears CSN pin of NRF24l01+ module.
Definition at line 47 of file nrf24l01.c.
References nrf_csn, nrf_gpio_base, and set_CSN().
Referenced by NRF_read(), and NRF_write().
ConfigureNRF()
void ConfigureNRF (void)
Configures NRF24l01+ module.
Definition at line 56 of file nrf24l01.c.
References ConfigureSPI2(), EN_RXADDR, FIFO_STATUS, FLUSH_RX, FLUSH_TX, NOP, nrf_ce, nrf_csn, nrf_gpio_base, nrf_irq, NRF_ISR(), NRF_read(), NRF_write(), R_REGISTER, RX_ADDR_P, RX_PW_P, SPI_rxfifo_flush(), TX_ADDR, and W_REGISTER.
Referenced by Comm_fn().
NRF_ISR()
void NRF_ISR (void)
ISR of NRF24l01+ module.
Definition at line 88 of file rf_comm.c.
Referenced by ConfigureNRF().
NRF_read()
uint8_t NRF_read (uint32_t command, uint8_t * data, uint8_t count)
Read from NRF24l01+ module.
Parameters
command NRF24l01+ command to read
data Pointer of data to receive
count Number of bytes of data to receive from above pointer
Returns
Status register value
Definition at line 169 of file nrf24l01.c.
References clear_CSN(), NOP, NRF_write(), set_CSN(), SPIreceive(), and SPIsend().
Referenced by Comm_fn(), ConfigureNRF(), and NRF_ISR().
NRF_write()
uint8_t NRF_write (uint32_t command, uint8_t * data, uint8_t count)
Write to NRF24l01+ module.
Parameters
command NRF24l01+ command to send
data Pointer of data to send
count Number of bytes of data to send from above pointer. count=0 for read commands
Returns
Status register value
Definition at line 132 of file nrf24l01.c.
References clear_CSN(), set_CSN(), SPI_rxfifo_flush(), SPIreceive(), and SPIsend().
Referenced by Comm_fn(), ConfigureNRF(), NRF_ISR(), NRF_read(), set_rxmode(), and set_txmode().
set_CE()
void set_CE ()
Sets CE pin of NRF24l01+ module.
Definition at line 31 of file nrf24l01.c.
References nrf_ce, and nrf_gpio_base.
Referenced by Comm_fn(), and NRF_ISR().
set_CSN()
void set_CSN ()
Sets CSN pin of NRF24l01+ module.
File: i2c_driver.c Author: Vatsal Sheth & Sarthak Jain Description: This file has driver API for NRF24l01+ module Date: 4/29/2019
Definition at line 23 of file nrf24l01.c.
References nrf_csn, and nrf_gpio_base.
Referenced by clear_CSN(), NRF_read(), and NRF_write().
set_rxmode()
void set_rxmode (void)
Set NRF module to RX mode.
Definition at line 118 of file nrf24l01.c.
References CONFIG, NRF_write(), and W_REGISTER.
Referenced by NRF_ISR().
set_txmode()
void set_txmode (void)
Set NRF module to TX mode.
Definition at line 108 of file nrf24l01.c.
References CONFIG, NRF_write(), and W_REGISTER.
Referenced by Comm_fn(), and Timer1IntHandler().