nrf24l01.c File Reference
#include `Include/nrf24l01.h`
Functions
void set_CSN ()
Sets CSN pin of NRF24l01+ module.
void set_CE ()
Sets CE pin of NRF24l01+ module.
void clear_CE ()
Clears CE pin of NRF24l01+ module.
void clear_CSN ()
Clears CSN pin of NRF24l01+ module.
void ConfigureNRF (void)
Configures NRF24l01+ module.
void set_txmode (void)
Set NRF module to TX mode.
void set_rxmode (void)
Set NRF module to RX mode.
uint8_t NRF_write (uint32_t command, uint8_t *data, uint8_t count)
Write to NRF24l01+ module.
uint8_t NRF_read (uint32_t command, uint8_t *data, uint8_t count)
Read from NRF24l01+ module.
Function Documentation
clear_CE()
void clear_CE ()
Clears CE pin of NRF24l01+ module.
Definition at line 39 of file nrf24l01.c.
References nrf_ce, and nrf_gpio_base.
Referenced by Comm_fn(), NRF_ISR(), and Timer1IntHandler().
clear_CSN()
void clear_CSN ()
Clears CSN pin of NRF24l01+ module.
Definition at line 47 of file nrf24l01.c.
References nrf_csn, nrf_gpio_base, and set_CSN().
Referenced by NRF_read(), and NRF_write().
ConfigureNRF()
void ConfigureNRF (void)
Configures NRF24l01+ module.
Definition at line 56 of file nrf24l01.c.
References ConfigureSPI2(), EN_RXADDR, FIFO_STATUS, FLUSH_RX, FLUSH_TX, NOP, nrf_ce, nrf_csn, nrf_gpio_base, nrf_irq, NRF_ISR(), NRF_read(), NRF_write(), R_REGISTER, RX_ADDR_P, RX_PW_P, SPI_rxfifo_flush(), TX_ADDR, and W_REGISTER.
Referenced by Comm_fn().
NRF_read()
uint8_t NRF_read (uint32_t command, uint8_t * data, uint8_t count)
Read from NRF24l01+ module.
Parameters
command NRF24l01+ command to read
data Pointer of data to receive
count Number of bytes of data to receive from above pointer
Returns
Status register value
Definition at line 169 of file nrf24l01.c.
References clear_CSN(), NOP, NRF_write(), set_CSN(), SPIreceive(), and SPIsend().
Referenced by Comm_fn(), ConfigureNRF(), and NRF_ISR().
NRF_write()
uint8_t NRF_write (uint32_t command, uint8_t * data, uint8_t count)
Write to NRF24l01+ module.
Parameters
command NRF24l01+ command to send
data Pointer of data to send
count Number of bytes of data to send from above pointer. count=0 for read commands
Returns
Status register value
Definition at line 132 of file nrf24l01.c.
References clear_CSN(), set_CSN(), SPI_rxfifo_flush(), SPIreceive(), and SPIsend().
Referenced by Comm_fn(), ConfigureNRF(), NRF_ISR(), NRF_read(), set_rxmode(), and set_txmode().
set_CE()
void set_CE ()
Sets CE pin of NRF24l01+ module.
Definition at line 31 of file nrf24l01.c.
References nrf_ce, and nrf_gpio_base.
Referenced by Comm_fn(), and NRF_ISR().
set_CSN()
void set_CSN ()
Sets CSN pin of NRF24l01+ module.
File: i2c_driver.c Author: Vatsal Sheth & Sarthak Jain Description: This file has driver API for NRF24l01+ module Date: 4/29/2019
Definition at line 23 of file nrf24l01.c.
References nrf_csn, and nrf_gpio_base.
Referenced by clear_CSN(), NRF_read(), and NRF_write().
set_rxmode()
void set_rxmode (void)
Set NRF module to RX mode.
Definition at line 118 of file nrf24l01.c.
References CONFIG, NRF_write(), and W_REGISTER.
Referenced by NRF_ISR().
set_txmode()
void set_txmode (void)
Set NRF module to TX mode.
Definition at line 108 of file nrf24l01.c.
References CONFIG, NRF_write(), and W_REGISTER.
Referenced by Comm_fn(), and Timer1IntHandler().