rf_comm.c File Reference
#include `Include/rf_comm.h`
Functions
uint32_t Comm_task ()
void Comm_fn (void *pvParameters)
void NRF_ISR (void)
ISR of NRF24l01+ module.
void ConfigureTIMER1 (void)
void setTIMER1 (uint8_t sec)
void Timer1IntHandler (void)
Variables
TaskHandle_t xHandle_rf
uint32_t tx_flag
uint32_t rx_flag
uint32_t max_flag
uint32_t tx_cont
uint32_t rf_link
struct tx_packet rx_pk
Function Documentation
Comm_fn()
void Comm_fn (void * pvParameters)
Definition at line 28 of file rf_comm.c.
References clear_CE(), ConfigureNRF(), ConfigureTIMER1(), Continue, max_flag, NRF_read(), NRF_write(), R_RX_PAYLOAD, rf_link, rx_flag, rx_pk, set_CE(), set_txmode(), tx_cont, tx_flag, W_TX_PAYLOAD, xQueue_a, and xQueue_rf.
Referenced by Comm_task().
Comm_task()
uint32_t Comm_task ()
Definition at line 15 of file rf_comm.c.
References Comm_fn(), configMAX_PRIORITIES, and xHandle_rf.
Referenced by main().
ConfigureTIMER1()
void ConfigureTIMER1 (void)
Definition at line 131 of file rf_comm.c.
Referenced by Comm_fn().
NRF_ISR()
void NRF_ISR (void)
ISR of NRF24l01+ module.
Definition at line 88 of file rf_comm.c.
References clear_CE(), max_flag, nrf_gpio_base, NRF_read(), NRF_write(), R_REGISTER, rf_link, rx_flag, set_CE(), set_rxmode(), setTIMER1(), STATUS, tx_cont, tx_flag, and W_REGISTER.
Referenced by ConfigureNRF().
setTIMER1()
void setTIMER1 (uint8_t sec)
Definition at line 139 of file rf_comm.c.
References g_ui32SysClock.
Referenced by NRF_ISR(), and Timer1IntHandler().
Timer1IntHandler()
void Timer1IntHandler (void)
Definition at line 145 of file rf_comm.c.
References clear_CE(), max_flag, rf_link, rx_flag, set_txmode(), setTIMER1(), and tx_flag.
Variable Documentation
max_flag
uint32_t max_flag
Definition at line 12 of file rf_comm.c.
Referenced by Comm_fn(), NRF_ISR(), and Timer1IntHandler().
rf_link
uint32_t rf_link
Definition at line 12 of file rf_comm.c.
Referenced by Actuator_fn(), Comm_fn(), NRF_ISR(), and Timer1IntHandler().
rx_flag
uint32_t rx_flag
Definition at line 12 of file rf_comm.c.
Referenced by Comm_fn(), NRF_ISR(), and Timer1IntHandler().
rx_pk
struct tx_packet rx_pk
Definition at line 13 of file rf_comm.c.
Referenced by Comm_fn().
tx_cont
uint32_t tx_cont
Definition at line 12 of file rf_comm.c.
Referenced by Comm_fn(), and NRF_ISR().
tx_flag
uint32_t tx_flag
Definition at line 12 of file rf_comm.c.
Referenced by Comm_fn(), NRF_ISR(), and Timer1IntHandler().
xHandle_rf
TaskHandle_t xHandle_rf
File: rf_comm.c Author: Vatsal Sheth & Sarthak Jain Description: This file creates task for rf comunication control Date: 4/29/2019
Definition at line 11 of file rf_comm.c.
Referenced by Actuator_fn(), and Comm_task().