Include/rf_comm.h File Reference
#include `nrf24l01.h`
Macros
#define Accident (0x01)
#define Time_exc (0x02)
#define N_ignore (0x04)
#define Continue (0x08)
#define GPS (0x10)
#define ACCEL (0x20)
Functions
void Comm_fn (void *pvParameters)
uint32_t Comm_task ()
void NRF_ISR (void)
ISR of NRF24l01+ module.
void ConfigureTIMER1 ()
void setTIMER1 (uint8_t sec)
Variables
QueueHandle_t xQueue_rf
QueueHandle_t xQueue_a
SemaphoreHandle_t xSemaphore_rf
TaskHandle_t xHandle_rf
uint32_t rf_link
Macro Definition Documentation
ACCEL
#define ACCEL (0x20)
Definition at line 18 of file rf_comm.h.
Accident
#define Accident (0x01)
File: rf_comm.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by rf_comm.c Date: 4/29/2019
Definition at line 13 of file rf_comm.h.
Continue
#define Continue (0x08)
Definition at line 16 of file rf_comm.h.
Referenced by Comm_fn().
GPS
#define GPS (0x10)
Definition at line 17 of file rf_comm.h.
N_ignore
#define N_ignore (0x04)
Definition at line 15 of file rf_comm.h.
Time_exc
#define Time_exc (0x02)
Definition at line 14 of file rf_comm.h.
Referenced by get_time().
Function Documentation
Comm_fn()
void Comm_fn (void * pvParameters)
Definition at line 28 of file rf_comm.c.
References clear_CE(), ConfigureNRF(), ConfigureTIMER1(), Continue, max_flag, NRF_read(), NRF_write(), R_RX_PAYLOAD, rf_link, rx_flag, rx_pk, set_CE(), set_txmode(), tx_cont, tx_flag, W_TX_PAYLOAD, xQueue_a, and xQueue_rf.
Referenced by Comm_task().
Comm_task()
uint32_t Comm_task ()
Definition at line 15 of file rf_comm.c.
References Comm_fn(), configMAX_PRIORITIES, and xHandle_rf.
Referenced by main().
ConfigureTIMER1()
void ConfigureTIMER1 ()
Definition at line 131 of file rf_comm.c.
Referenced by Comm_fn().
NRF_ISR()
void NRF_ISR (void)
ISR of NRF24l01+ module.
Definition at line 88 of file rf_comm.c.
References clear_CE(), max_flag, nrf_gpio_base, NRF_read(), NRF_write(), R_REGISTER, rf_link, rx_flag, set_CE(), set_rxmode(), setTIMER1(), STATUS, tx_cont, tx_flag, and W_REGISTER.
setTIMER1()
void setTIMER1 (uint8_t sec)
Definition at line 139 of file rf_comm.c.
References g_ui32SysClock.
Referenced by NRF_ISR(), and Timer1IntHandler().
Variable Documentation
rf_link
uint32_t rf_link
Definition at line 12 of file rf_comm.c.
Referenced by Comm_fn(), NRF_ISR(), and Timer1IntHandler().
xHandle_rf
TaskHandle_t xHandle_rf
File: rf_comm.c Author: Vatsal Sheth & Sarthak Jain Description: This file creates task for rf comunication control Date: 4/29/2019
Definition at line 11 of file rf_comm.c.
Referenced by Comm_task().
xQueue_a
QueueHandle_t xQueue_a
Definition at line 12 of file main.c.
xQueue_rf
QueueHandle_t xQueue_rf
File: main.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by main.c Date: 4/29/2019
Definition at line 12 of file main.c.
xSemaphore_rf
SemaphoreHandle_t xSemaphore_rf
Definition at line 13 of file main.c.