sensor.c File Reference
#include `Include/sensor.h`
Functions
void Sensor_fn (void *pvParameters)
uint32_t Sensor_task ()
void ConfigureTIMER (void)
void Timer0IntHandler (void)
uint32_t get_time ()
Variables
uint32_t button_flag
uint32_t time_exch_flag
struct tx_packet pk
TaskHandle_t xHandle_s
Function Documentation
ConfigureTIMER()
void ConfigureTIMER (void)
Definition at line 99 of file sensor.c.
References g_ui32SysClock.
Referenced by Sensor_fn().
get_time()
uint32_t get_time ()
Definition at line 118 of file sensor.c.
References pk, and Time_exc.
Referenced by Sensor_fn().
Sensor_fn()
void Sensor_fn (void * pvParameters)
Definition at line 14 of file sensor.c.
References button_flag, ConfigureButton(), ConfigureMPU(), ConfigureTIMER(), ConfigureUART_4_GPS(), get_time(), gps_encode(), gps_f_get_position(), gps_satellites(), pk, time_exch_flag, xQueue_a, xQueue_rf, and xSemaphore_s.
Referenced by Sensor_task().
Sensor_task()
uint32_t Sensor_task ()
Definition at line 86 of file sensor.c.
References configMAX_PRIORITIES, Sensor_fn(), and xHandle_s.
Referenced by main().
Timer0IntHandler()
void Timer0IntHandler (void)
Definition at line 110 of file sensor.c.
References xSemaphore_s.
Variable Documentation
button_flag
uint32_t button_flag
File: sensor.c Author: Vatsal Sheth & Sarthak Jain Description: This file creates task for sensors which control GPS, MPU6050, button Date: 4/29/2019
Definition at line 10 of file sensor.c.
Referenced by Button_ISR(), MPU_ISR(), and Sensor_fn().
pk
struct tx_packet pk
Definition at line 11 of file sensor.c.
Referenced by Button_ISR(), get_time(), MPU_ISR(), and Sensor_fn().
time_exch_flag
uint32_t time_exch_flag
Definition at line 10 of file sensor.c.
Referenced by MPU_ISR(), and Sensor_fn().
xHandle_s
TaskHandle_t xHandle_s
Definition at line 12 of file sensor.c.
Referenced by Actuator_fn(), and Sensor_task().