Include/sensor.h File Reference
#include <string.h>
#include `mpu6050.h`
#include `uart_driver.h`
#include `button.h`
#include `gps_driver.h`
Macros
#define Accident (0x01)
#define Time_exc (0x02)
#define N_ignore (0x04)
#define Continue (0x08)
#define GPS (0x10)
#define ACCEL (0x20)
Functions
uint32_t Sensor_task ()
void Sensor_fn (void *pvParameters)
void ConfigureTIMER (void)
uint32_t get_time ()
Variables
QueueHandle_t xQueue_rf
QueueHandle_t xQueue_a
SemaphoreHandle_t xSemaphore_rf
SemaphoreHandle_t xSemaphore_s
uint32_t time_exch_flag
uint32_t button_flag
struct tx_packet pk
TaskHandle_t xHandle_s
uint32_t timer_flag
Macro Definition Documentation
ACCEL
#define ACCEL (0x20)
Definition at line 22 of file sensor.h.
Accident
#define Accident (0x01)
File: sensor.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by sensor.c Date: 4/29/2019
Definition at line 17 of file sensor.h.
Continue
#define Continue (0x08)
Definition at line 20 of file sensor.h.
GPS
#define GPS (0x10)
Definition at line 21 of file sensor.h.
N_ignore
#define N_ignore (0x04)
Definition at line 19 of file sensor.h.
Time_exc
#define Time_exc (0x02)
Definition at line 18 of file sensor.h.
Function Documentation
ConfigureTIMER()
void ConfigureTIMER (void)
Definition at line 99 of file sensor.c.
References g_ui32SysClock.
Referenced by Sensor_fn().
get_time()
uint32_t get_time ()
Definition at line 118 of file sensor.c.
References pk, and Time_exc.
Referenced by Sensor_fn().
Sensor_fn()
void Sensor_fn (void * pvParameters)
Definition at line 14 of file sensor.c.
References button_flag, ConfigureButton(), ConfigureMPU(), ConfigureTIMER(), ConfigureUART_4_GPS(), get_time(), gps_encode(), gps_f_get_position(), gps_satellites(), pk, time_exch_flag, xQueue_a, xQueue_rf, and xSemaphore_s.
Referenced by Sensor_task().
Sensor_task()
uint32_t Sensor_task ()
Definition at line 86 of file sensor.c.
References configMAX_PRIORITIES, Sensor_fn(), and xHandle_s.
Referenced by main().
Variable Documentation
button_flag
uint32_t button_flag
File: sensor.c Author: Vatsal Sheth & Sarthak Jain Description: This file creates task for sensors which control GPS, MPU6050, button Date: 4/29/2019
Definition at line 10 of file sensor.c.
Referenced by Sensor_fn().
pk
struct tx_packet pk
Definition at line 11 of file sensor.c.
Referenced by get_time(), and Sensor_fn().
time_exch_flag
uint32_t time_exch_flag
Definition at line 10 of file sensor.c.
Referenced by Sensor_fn().
timer_flag
uint32_t timer_flag
Definition at line 30 of file sensor.h.
xHandle_s
TaskHandle_t xHandle_s
Definition at line 12 of file sensor.c.
Referenced by Sensor_task().
xQueue_a
QueueHandle_t xQueue_a
Definition at line 12 of file main.c.
Referenced by main().
xQueue_rf
QueueHandle_t xQueue_rf
File: main.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by main.c Date: 4/29/2019
Definition at line 12 of file main.c.
Referenced by main().
xSemaphore_rf
SemaphoreHandle_t xSemaphore_rf
Definition at line 13 of file main.c.
Referenced by main().
xSemaphore_s
SemaphoreHandle_t xSemaphore_s
Definition at line 13 of file main.c.
Referenced by main().