Include/spi_driver.h File Reference
#include `basic.h`
#include `driverlib/ssi.h`
Functions
void ConfigureSPI2 (void)
Configure SSI2 block as SPI Master.
void SPIsend (uint32_t *data, uint32_t count)
Send data through SSI2.
void SPIreceive (uint32_t *data, uint32_t count)
Receive data through SSI2.
void SPI_rxfifo_flush (void)
Function Documentation
ConfigureSPI2()
void ConfigureSPI2 (void)
Configure SSI2 block as SPI Master.
File: spi_driver.h Author: Vatsal Sheth & Sarthak Jain Description: This file contains required include and declarations of variables and functions used by spi_driver.c Date: 4/29/2019
File: actuator.c Author: Vatsal Sheth & Sarthak Jain Description: This file contains API for SPI Date: 4/29/2019
Definition at line 19 of file spi_driver.c.
References g_ui32SysClock.
Referenced by ConfigureNRF().
SPI_rxfifo_flush()
void SPI_rxfifo_flush (void)
Definition at line 78 of file spi_driver.c.
Referenced by ConfigureNRF(), and NRF_write().
SPIreceive()
void SPIreceive (uint32_t * data, uint32_t count)
Receive data through SSI2.
Parameters
data Pointer to store received data
count Number of 32 bits data to receive
Definition at line 67 of file spi_driver.c.
Referenced by NRF_read(), and NRF_write().
SPIsend()
void SPIsend (uint32_t * data, uint32_t count)
Send data through SSI2.
Parameters
data Pointer to send data
count Number of 32 bits data to send
Definition at line 48 of file spi_driver.c.
Referenced by NRF_read(), and NRF_write().